---
kind: pipeline
type: docker
name: ci

steps:
  - name: install
    image: node:16.13.2
    commands:
      - yarn --silent
    when:
      branch:
        - master
      event:
        - push

  - name: lint
    image: node:16.13.2
    commands:
      - yarn lint
    when:
      branch:
        - master
      event:
        - push

  - name: typecheck
    image: node:16.13.2
    commands:
      - yarn tsc --project ./tsconfig.json
    when:
      branch:
        - master
      event:
        - push

  - name: build/npm-package
    image: node:16.13.2
    commands:
      - yarn build:dist
    when:
      branch:
        - master
      event:
        - push

  - name: publish/npm-package
    image: plugins/npm
    settings:
      username:
        from_secret: npm_username
      password:
        from_secret: npm_password
      email:
        from_secret: npm_email
      token:
        from_secret: npm_token
    when:
      branch:
        - master
      event:
        - push
