---
kind: pipeline
type: docker
name: ci

steps:
  - name: install
    image: iknpx/archnode
    commands:
      - yarn --silent
    when:
      branch:
        - master
      event:
        - push

  - name: lint
    image: iknpx/archnode
    commands:
      - yarn lint:check
    when:
      branch:
        - master
      event:
        - push

  - name: build/npm-package
    image: iknpx/archnode
    commands:
      - yarn dist
    when:
      branch:
        - master
      event:
        - push

  - name: publish/npm-package
    image: plugins/npm
    settings:
      username:
        from_secret: npm_username
      password:
        from_secret: npm_password
      email:
        from_secret: npm_email
      token:
        from_secret: npm_token
    when:
      branch:
        - master
      event:
        - push